- name: Update and upgrade packages on target hosts
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Display the host's name
      debug:
        msg: "HOSTNAME : {{ ansible_hostname }}"
- name: Show disk usage using df -h
  hosts: all
  tasks:
    - name: Run df -h to check disk usage
      command: df -h
      register: disk_usage

    - name: Display disk usage output
      debug:
        msg: "{{ disk_usage.stdout }}"
