- name: Update and upgrade packages on target hosts
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Display the host's name
      debug:
        msg: "HOSTNAME : {{ ansible_hostname }}"


- name: Display PC Components: CPU, Cores, RAM, and OS
  hosts: all
  tasks:
    - name: Gather all system facts
      setup:

    - name: Display CPU information
      debug:
        msg: "CPU Model: {{ ansible_processor[0] }}"

    - name: Display number of CPU cores
      debug:
        msg: "CPU Cores: {{ ansible_processor_cores | default(ansible_processor_vcpus) }}"

    - name: Display total memory
      debug:
        msg: "Total Memory (MB): {{ ansible_memtotal_mb }}"

    - name: Display operating system information
      debug:
        msg: "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
