- name: Update and upgrade packages on target hosts
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Display the host's name
      debug:
        msg: "HOSTNAME : {{ ansible_hostname }}"
