- hosts: gmod
  become: false
  tasks:
    - name: Check if GMod server is running
      ansible.builtin.command: ./gmodserver status
      args:
        chdir: /home/gmodserver
      register: gmod_status
      ignore_errors: true

    - name: Start GMod server if not running
      ansible.builtin.command: ./gmodserver start
      args:
        chdir: /home/gmodserver
      when: gmod_status.rc != 0

      
- hosts: cs2
  become: false   # no sudo needed
  tasks:
    - name: Start Cs2 server as cs2server duh
      ansible.builtin.shell: ./cs2server start
      args:
        chdir: /home/cs2server
      # Only run if the remote user is gmodserver
      when: ansible_user == 'cs2server'


- hosts: css
  become: false   # no sudo needed
  tasks:
    - name: Start Css server as cssserver duh
      ansible.builtin.shell: ./cssserver start
      args:
        chdir: /home/cssserver
      # Only run if the remote user is gmodserver
      when: ansible_user == 'cssserver'
