- hosts: gmod
  become: false
  tasks:
    - name: Check if GMod server is running
      ansible.builtin.command: ./gmodserver monitor
      args:
        chdir: /home/gmodserver
      register: gmod_status
      ignore_errors: true

    - name: Start GMod server if not running
      ansible.builtin.command: ./gmodserver start
      args:
        chdir: /home/gmodserver
      when: gmod_status.rc != 0

      
- hosts: cs2
  become: false   # no sudo needed
  tasks:
    - name: Check if Cs2 server is running
      ansible.builtin.command: ./cs2server monitor
      args:
        chdir: /home/cs2server
      register: cs2_status
      ignore_errors: true

    - name: Start Cs2 server if not running
      ansible.builtin.command: ./cs2server start
      args:
        chdir: /home/cs2server
      when: cs2_status.rc != 0


- hosts: css
  become: false   # no sudo needed
  tasks:
    - name: Check if Css server is running
      ansible.builtin.command: ./cssserver monitor
      args:
        chdir: /home/cssserver
      register: css_status
      ignore_errors: true

    - name: Start Css server if not running
      ansible.builtin.command: ./cssserver start
      args:
        chdir: /home/cssserver
      when: css_status.rc != 0

- name: Youtube Downloader
  hosts: ytd
  become: true
  tasks:
    - name: Run app.py in background
      shell: nohup python3 ./app.py > app.log 2>&1 &
      args:
        chdir: /var/www/html

