- hosts: gmod
  become: false
  tasks:
    - name: Check if GMod server is running
      ansible.builtin.command: ./gmodserver monitor
      args:
        chdir: /home/gmodserver
      register: gmod_status
      ignore_errors: true

    - name: Start GMod server if not running
      ansible.builtin.command: ./gmodserver start
      args:
        chdir: /home/gmodserver
      when: gmod_status.rc != 0

      
- hosts: dayz
  become: false   # no sudo needed
  tasks:
    - name: Check if dayz server is running
      ansible.builtin.command: ./dayzserver monitor
      args:
        chdir: /home/dayzserver
      register: dayz_status
      ignore_errors: true

    - name: Start Dayz server if not running
      ansible.builtin.command: ./dayzserver start
      args:
        chdir: /home/dayzserver
      when: dayz_status.rc != 0



- name: Ensure app.py is running in background on ytd
  hosts: ytd
  become: true
  tasks:
    - name: Check if app.py is already running
      shell: |
        cd /var/www/html && pgrep -x python3 | xargs -r ps -o args= -p | grep -q "python3 ./app.py"
      register: app_status
      ignore_errors: true

    - name: Start app.py if not running
      shell: nohup python3 ./app.py > app.log 2>&1 &
      args:
        chdir: /var/www/html
      when: app_status.rc != 0

      

