- hosts: gmod
  become: false   # no sudo needed
  tasks:
    - name: Start GMod server as gmodserver
      ansible.builtin.shell: ./gmodserver start
      args:
        chdir: /home/gmodserver
      # Only run if the remote user is gmodserver
      when: ansible_user == 'gmodserver'

      
- hosts: cs2
  become: false   # no sudo needed
  tasks:
    - name: Start Cs2 server as cs2server duh
      ansible.builtin.shell: ./cs2server start
      args:
        chdir: /home/cs2server
      # Only run if the remote user is gmodserver
      when: ansible_user == 'cs2server'


- hosts: css
  become: false   # no sudo needed
  tasks:
    - name: Start Css server as cssserver duh
      ansible.builtin.shell: ./cssserver start
      args:
        chdir: /home/cssserver
      # Only run if the remote user is gmodserver
      when: ansible_user == 'cssserver'
